/*
 * fsp_frame.h
 *
 *  Created on: May 8, 2026
 *      Author: PV
 */

#ifndef FSP_LINE_TASK_FSP_FRAME_H_
#define FSP_LINE_TASK_FSP_FRAME_H_

typedef enum _FSP_CMD_typedef_
{
	/* :::::::::: Pulse Control Command :::::::: */
	FSP_CMD_SET_SEQUENCE_INDEX,
	FSP_CMD_SET_SEQUENCE_CONFIRM,
	FSP_CMD_SET_SEQUENCE_DELETE,
	FSP_CMD_SET_SEQUENCE_DELAY,

	FSP_CMD_SET_PULSE_POLE,
	FSP_CMD_SET_PULSE_COUNT,
	FSP_CMD_SET_PULSE_DELAY,
	FSP_CMD_SET_PULSE_HV_POS,
	FSP_CMD_SET_PULSE_HV_NEG,
	FSP_CMD_SET_PULSE_LV_POS,
	FSP_CMD_SET_PULSE_LV_NEG,
	FSP_CMD_SET_PULSE_CONTROL,
	FSP_CMD_GET_PULSE_STAGE,

	/* :::::::::: Auto Accel Command :::::::: */
	FSP_CMD_SET_AUTO_ACCEL,
	FSP_CMD_SET_THRESHOLD_ACCEL,
	FSP_CMD_GET_THRESHOLD_ACCEL,
	FSP_CMD_STREAM_ACCEL,

	/* :::::::::: Manual Pulse Command :::::::: */
	FSP_CMD_SET_MANUAL_POLE,
	FSP_CMD_SET_MANUAL_CAP,
	FSP_CMD_SET_MANUAL_PULSE,

	/* :::::::::: VOM Command :::::::: */
	FSP_CMD_MEASURE_VOLT,
	FSP_CMD_MEASURE_CURRENT,
	FSP_CMD_MEASURE_IMPEDANCE,

	/* :::::::::: OVC Signal :::::::: */
	FSP_CMD_SET_CURRENT_LIMIT,
	FSP_CMD_OVER_CURRENT_DETECT,

	FSP_CMD_GET_OVC_FLAG,

	/* :::::::::: I2C Sensor Command :::::::: */
	FSP_CMD_GET_SENSOR_GYRO,
	FSP_CMD_GET_SENSOR_ACCEL,
	FSP_CMD_GET_SENSOR_LSM6DSOX,

	FSP_CMD_GET_SENSOR_TEMP,
	FSP_CMD_GET_SENSOR_PRESSURE,
	FSP_CMD_GET_SENSOR_ALTITUDE,
	FSP_CMD_GET_SENSOR_BMP390,

	FSP_CMD_GET_SENSOR_H3LIS331DL,


	/* :::::::::: Ultility Command :::::::: */
	FSP_CMD_HANDSHAKE,

} FSP_CMD_typedef;

#endif /* FSP_LINE_TASK_FSP_FRAME_H_ */
